generator:
  class: sfDoctrineGenerator
  param:
    model_class:           sfGuardUser
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          sf_shibboleth_user
    with_doctrine_route:     1

    config:
      actions: ~
      fields:  ~
      list:
        title:   User list
        display: [=username, created_at, updated_at, last_login]
      form:
        class: sfGuardUserAdminForm
        display:
          "NONE":                   [username]
          "Permissions and groups": [is_active, is_super_admin, groups_list, permissions_list]
      edit:
        title: Editing User "%%username%%"
      new:
        title: New User